name: Snapshot Docker Image

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.2.0
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: docker-molecule-buildx

      - name: Build the docker image
        env:
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          echo "${DOCKERHUB_ACCESS_TOKEN}" | docker login --username borisskert --password-stdin
          docker buildx build . \
                       --pull \
                       --file Dockerfile \
                       --tag borisskert/molecule:snapshot \
                       --cache-from "type=local,src=/tmp/.buildx-cache" \
                       --cache-to "type=local,dest=/tmp/.buildx-cache" \
                       --output "type=image,push=true" \
                       --platform=linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
